### ISSUE TITLE
fix: 메뉴 상세 페이지 맛 태그 순서 변동

### ISSUE THREAD

**Issue by chogyejin** [prgrms-web-devcourse/Team-Tasty-Masiottae-FE#166]
#### 제목:
메뉴를 fetch 해오는 상황에서 해당 메뉴의 맛 태그 리스트의 순서가 보장되지 않습니다.

**Comment by nyoung113** [comment]
이거 be에게 한번 물어보시면 좋을 것 같아요! tasteList를 가져올 때에는 순서 보장이 되는데 menu 조회할 때에는 계진님 말씀 처럼 순서 보장이 안되는 것 같아요
